### ISSUE TITLE
RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented

### ISSUE THREAD

**Issue by yosiah-morgan** [eps696/stylegan2ada#10]
Thank you for the repository! I'm using it as part of a final for one of my media classes.
I keep getting the following exception:
<img width="1205" alt="RuntimeError: derivative for aten::grid_sampler_2d_backward is not implemented" src="https://user-images.githubusercontent.com/18102928/141693067-e1fc6db3-6b30-4669-a139-542891723fe7.png">
Tried making sure that I was using Torch 1.7.1 and Python 3.8 but still get the exception.

**Comment by eps696** [comment]
did you really make sure you're running pytorch 1.7.1? 
this problem was reported (as probably non-fixable) on pt 1.9, didn't face it on earlier versions 
see also :: https://github.com/eps696/stylegan2ada/issues/5

**Comment by yosiah-morgan** [comment]
I created a clean environment to instal pt 1.7.1 and it's working fine now, sorry about that. Thank you for your help!

**Comment by eps696** [comment]
just for the records: this is fixed now [tested on pytorch 1.10]
