### ISSUE TITLE
error when trying to fine tune 1280x768 model 

### ISSUE THREAD

**Issue by devilmaycry777** [eps696/stylegan2ada#12]
Hi!

I'm trying to fine tune a model i found here: https://thisbeachdoesnotexist.com/

Model specs: 

StyleGAN2-Ada
Dataset	20.000 images
Network size	362 MB
Resolution	1280×768 px
Network layout	5×3 squares (with 28 = 256 px sides)
Training options	--min_w=5 --min_h=3 --res_log2=8
Trained using	RoyWheels/stylegan2-ada (github)
Training steps	25.000 kimg
Metric FID50k	3.14

I get this warning 

Resuming from "/G/MyDrive/sg2a_eps/train/beach-network-snapshot-025000.pkl", kimg 0
 warning: unknown TF kwargs ['res_log2', 'min_w', 'min_h']

and then this error 

AssertionError                            Traceback (most recent call last)
/G/MyDrive/sg2a_eps/src/train.py in <module>()
    407     __spec__ = "ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>)"
    408 
--> 409     main() # pylint: disable=no-value-for-parameter
    410 

13 frames
/G/MyDrive/sg2a_eps/src/training/networks.py in __init__(self, w_dim, img_resolution, img_channels, init_res, channel_base, channel_max, num_fp16_res, **block_kwargs)
    451         **block_kwargs,             # Arguments for SynthesisBlock.
    452     ):
--> 453         assert img_resolution >= 4 and img_resolution & (img_resolution - 1) == 0
    454         super().__init__()
    455         self.w_dim = w_dim

AssertionError: 

My dataset is in 1280x768.
I've been able to train with my dataset from scratch, but having this problem when doing transfer learning from this beach model.

Thank You!

**Comment by eps696** [comment]
unfortunately, that model was trained on the very customized network from https://github.com/RoyWheels/stylegan2-ada.
the author decided to rename all vars/layers according to their real resolutions - which made his models effectively incompatible with nvidia var naming [which i follow in my repo]. there are more differences and inconsistencies between @RoyWheels and nvidia hyperparameters, which i could address to make it work, but it's quite out of my scope to dig into layers conversion issues. 
thus, if you want to use that model, do it with its original repo.
