### ISSUE TITLE
is it posible to resume aug value when resuming training ?

### ISSUE THREAD

**Issue by devilmaycry777** [eps696/stylegan2ada#13]
Hi!

I wanted to know if its posible to resume aug and kimg value from latest training when resuming training.

Thank you!

**Comment by eps696** [comment]
current kimg value [resuming from] is auto-picked, when resuming from the training directory. 
alas, i see no reason for keeping the training hyperparams - like total kimg or aug specs - between runs, as they may (and usually do) change between runs.

**Comment by devilmaycry777** [comment]
> current kimg value [resuming from] is auto-picked, when resuming from the training directory. alas, i see no reason for keeping the training hyperparams - like total kimg or aug specs - between runs, as they may (and usually do) change between runs.

The kimg value is unnecesary.. but i found really useful to resume aug probability value from latest training. Say your latest training ended in 0.5 prob value, when i resume i want to start from 0.5 and not from 0.

Is it possible to do this?

thx

**Comment by eps696** [comment]
you can add whatever parameter you feel useful to the command line arguments in the corresponding cell, like `%run src/train.py --p 0.5 ..`
i have never used that probability myself, and will not dig into this, my apologies.
