### ISSUE TITLE
Cant change aspect ratio to square

### ISSUE THREAD

**Issue by corranmac** [eps696/stylegan2ada#16]
Hi there, Im trying to change a 512x1024 model into a 1024x1024 model, it says success and outputs a model but its size is still 512x1024 or atleast when I try to infer at 1024x1024 it gives me the error:
size mismatch for noises.noise_16: copying a param with shape torch.Size([1, 1, 1024, 512]) from checkpoint, the shape in current model is torch.Size([1, 1, 1024, 1024]).

Thanks!

**Comment by eps696** [comment]
where was that model trained (which repo)? how many layers does it contain?
the reason might be that the base resolution of the model was calculated differently in your model [e.g. 512] and my repo [1024]. 
if you want to finetune it, i'd try first changing it to 512x512, then to 1024x1024 [you'll get random weights on the last layer at this, which is ok for finetuning].

**Comment by corranmac** [comment]
Hi there, thank you very much for the reply! 
I didn't train the model myself so unfortunately dont know all its details but it was trained in Stylegan2-ada with eight mapping layers. Is there a way to manually feed in the models base resolution?
When I change the res_in in model_convert.py or reconstruct the model it gives me the error:
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 2

**Comment by eps696** [comment]
alas, i can't tell much without knowing the structure of your [input] model. 
one need to know amount of **generator** layers, not mapping ones.
in the meantime there's no way to feed base resolution `res_in` manually, it's calculated from the model's output shape.
