### ISSUE TITLE
Individual changes.

### ISSUE THREAD

**Issue by GilesBathgate** [eps696/stylegan2ada#17]
Your commits seem to have very brief descriptions, and I can't find the changes specific to the features you've added. I'd like to take just the changes relating to non-square aspect ratio support.

Would it be possible for you to help me isolate these changes and put them in a separate branch?

**Comment by eps696** [comment]
alas, i can hardly help with branches, as i'm not a pro developer and have tough time dealing with git. 
for the layers geometry tweaks you can follow the lines marked with `# !!! custom` in https://github.com/eps696/stylegan2ada/blob/master/src/training/stylegan2_multi.py - those were my changes to the original nvidia code. 
let me know if you have more specific questions.

**Comment by GilesBathgate** [comment]
Fair enough, that's an interesting approach. The idea of `git` is so you can put what you've changed into the commit messages, instead of into the code comments. I'll take a look at the comments.

**Comment by eps696** [comment]
alas, that's not an approach but a fault ::] sorry for that.
also, the changes which you mentioned [and the corresponding comments] were in this code from the very beginning - it was not a gradual update from the nvidia sources, but a publication of the working stuff - so there were no special commits for them.

**Comment by GilesBathgate** [comment]
I think the changes for non-square came from https://github.com/RoyWheels/stylegan2-ada who in turn adapted them from https://github.com/skyflynil/stylegan2

**Comment by eps696** [comment]
nope. the ones in my code [for training aspect and arbitrary size generation] were all mine. 
those were inherited from my previous repo https://github.com/eps696/stylegan2 and the progressive GAN stuff [not published]
