### ISSUE TITLE
Is it possible to turn of mirroring  ?

### ISSUE THREAD

**Issue by mothormothormothor** [eps696/stylegan2ada#20]
I'm trying to keep an image compositon while training, but the notebook keeps adding mirrored copies of my dataset. Is there a way to turn this of ? I've searched the code but haven't found a solution yet.

xoxo
Moto

![screen_mirror_eps](https://user-images.githubusercontent.com/105822353/187446007-839f815d-ab13-4ed2-aa0c-d490ed92a637.JPG)

**Comment by eps696** [comment]
ok, i've added back this option to the main code [it was broken unintentionally].
to switch off the mirroring add `--mirror False` to the command line inside the corresponding cell, e.g.:
`%run src/train.py --data $data_dir --kimg $kimg --mirror False`

**Comment by mothormothormothor** [comment]
Awesome! I just tested this and it works fine.
Thanks a lot!!
-closed-
