### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by aravind598** [eps696/stylegan2ada#22]
Hi, thank you for the excellent repo. I have a query about the train.py file, does the train.py use the StyleGAN2-ADA network from network.py or stylegan2_multi.py file because I see 2 different Generator Classes defined in each of the files? Also, apologies if this is a trivial question.

**Comment by eps696** [comment]
hi, thanks for appreciation.
`train.py` uses `network.py` [with fixed non-square aspect ratios addition], while `stylegan2_multi.py` [with multi-latent blending in arbitrary resolution] is used for the inference.

**Comment by aravind598** [comment]
Hi thanks you very much for the clarification but can i ask about the training times for non-square images like 512x1024 would it be between 512x512 and 1024x1024 or would it be longer than 512x1024

**Comment by eps696** [comment]
not sure if i got the question; the training time for 512x1024 should definitely fit within the range of corresponding values for 512 and 1024 square data, yet i didn't conduct any special profiling on that

**Comment by aravind598** [comment]
Thanks for your prompt response, I was just wondering if the training times of 512x512 < 512x1024 < 1024x1024 because the training images are not square and if internal padding occurs in the convolutional blocks, is just a dumb question by me apologies.
