### ISSUE TITLE
Where can I get ffhq-512.pkl?

### ISSUE THREAD

**Issue by vijishmadhavan** [eps696/stylegan2ada#23]
Can it be used to train RGBA images?

**Comment by eps696** [comment]
you can get "professional-grade" ffhq model in 1024 resolution from nvidia repo. i don't have public links to such model in 512. such filename might be used as an example in this repo though, which didn't imply any really existing file. 

if you need to adjust model to another resolution or aspect ratio, have a look on "tweaking models" section [in the readme or colab notes] of this repo. there is also an option to add alpha channel to the model to train it as rgba.
