### ISSUE TITLE
Kimg needs to be specified

### ISSUE THREAD

**Issue by trippyml** [eps696/stylegan2ada#4]
Thanks for setting this up. Trying this on rbga images, so hoping it works. Just as an fyi, unlike stylegan2-ada it looks like the kimg arg needs to be specified when training otherwise it breaks. Should it be defaulted?

**Comment by trippyml** [comment]
Closing as I saw it's specified in the readme.

**Comment by BishwaBS** [comment]
@trippyml did you train on the rgba image successfully? If yes, were you able to generate rgba images out of your trained model? Appreciate your suggestions here if any!
