### ISSUE TITLE
RuntimeError: derivative for grid_sampler_2d_backward is not implemented

### ISSUE THREAD

**Issue by florianbepunkt** [eps696/stylegan2ada#5]
Thank you for your repos. While the TF version runs on Colab, running the Pytorch version throws the following exception on Colab

`RuntimeError: derivative for grid_sampler_2d_backward is not implemented`

**Comment by eps696** [comment]
thanks for reporting. which situation/operation caused this? (what did you do before that)

**Comment by eps696** [comment]
it seems bound to recent torch 1.9 update, so ensured reinstalling 1.7.1 at the beginning.
[considering [this](https://github.com/pytorch/pytorch/issues/34704), it doesn't look like easily fixable otherwise]
should work now, reopen issue if not.

**Comment by eps696** [comment]
just for the records: this is fixed now [tested with pytorch 1.10]
