### ISSUE TITLE
Seed usage

### ISSUE THREAD

**Issue by trippyml** [eps696/stylegan2ada#7]
Similar to the `stylegan2-ada` repo, is it possible to specify seeds when using the generate script? 

ie `gen.bat ffhq-1024.pkl --seeds=0-100`

**Comment by eps696** [comment]
it's possible to add some seed control to ensure repeating results when needed. 

please note though, this repo lacks some generation options wrt the original repo, including the mentioned one. i generate only video/sequences ("latent walks"), not dealing with separate images at all (as i never faced such necessity in real projects). this was discussed and explained at [the other repo](https://github.com/eps696/stylegan2/issues/1) while ago. 

please let me know, if i miss something, and there's a serious reason to bring such demo-functionality from nvidia back here.

**Comment by trippyml** [comment]
`it's possible to add some seed control to ensure repeating results when needed.`

Thanks for your quick reply. Can you elaborate on the above? My main use-case is like you said...repeating the same results when needed. I'm fairly new to this space, so any guidance is appreciated! If you point me to the right direction, I can pick it up from there.

**Comment by eps696** [comment]
ok, added `--seed X` option to command line and the form entry to colab. 
set it to some positive integer to fix results (0 = random).
let me know if it solved the issue in your case.

**Comment by trippyml** [comment]
Thank you!
