### ISSUE TITLE
I am training on RGBA images. Do we have a pre-trained model (ffhq-256.pkl) that support RGBA on this version of yours?

### ISSUE THREAD

**Issue by BishwaBS** [eps696/stylegan2ada#9]

**Comment by eps696** [comment]
you can easily construct such model yourself from the standard (RGB) ffhq-256.pkl or ffhq-1024.pkl model, using scripts from the [previous repo](https://github.com/eps696/stylegan2) (see "Tweaking models" part). then it can be finetuned with any of these repos.

**Comment by BishwaBS** [comment]
I converted one of the pre-trained .pkl using `!python src/model_convert.py --source train/stylegan2-cat-config-f.pkl --alpha`.
When I tried to use the converted .pkl file `stylegan2-cat-config-f-256x256a.pkl` with this repo, it throws error as below `RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 0`. Any idea? I am sure I tweaked the 256*256 model.

**Comment by eps696** [comment]
what exactly do you mean by "tried to use"? which command did you run

**Comment by eps696** [comment]
thanks for reporting. i got this error as well, trying to finetune such converted model in this repo. 
the reason: fmaps (base conv filters count) in pytorch-ada version is halved for resolutions < 512. 
i've added to `train.py` an argument `--fmaps_fix` to match the models, coming from original stylegan2 repo (`off` by default). 
please confirm, if this fixed the problem on your side.

**Comment by simonmaris** [comment]
I don't want to hijack this, but just to clarify: The old model_convert script does not work with pkls trained using stylegan2-ada-pytorch, right? I would like to finetrain an existing 1024 model on a new RGBA dataset.

**Comment by eps696** [comment]
@simonmaris yes, it's stated in both mine and original nvidia repos: there is only forward compatibility between tf and pytorch versions. that means, old tf models (original or tweaked) can be used in ada-pytorch repo, but ada-pytorch models cannot be used in tf version (including its models tweaking scripts). in other words, tweaks for further finetuning are available only for tf-trained models.

**Comment by eps696** [comment]
i presume, the original problem is addressed, so am closing the issue for now. feel free to reopen, in case of remaining related questions.
